version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:your-app-key-here
      DB_CONNECTION: mariadb
      DB_HOST: mariadb.dev.atlindo.com
      DB_PORT: 80
      DB_DATABASE: theme_app
      DB_USERNAME: root
      DB_PASSWORD: @Admin123
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"
    volumes:
      - ./:/var/www/html

volumes:
  dbdata:
    driver: local
