export const ON_SAVE_THEME = 'ON-SAVE-THEME';
export const ON_CHANGE_LOCALE = 'THEME/LOCALE'
export const REHYDRATE_THEME_CONFIG = 'THEME/REHYDRATE_THEME_CONFIG'
export const ON_CHANGE_NAV_COLLAPSED = 'THEME/COLLAPSED'
